
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 147
#define YY_END_OF_BUFFER 148
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[359] =
    {   0,
        0,    0,    0,    0,    0,    0,  148,  146,  145,  145,
       42,  123,   44,   54,   46,  146,   59,   60,   47,   48,
       39,   49,   41,   50,  106,  105,   40,   56,   38,   55,
      144,  144,   61,   45,   62,   51,   53,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,   57,   52,   58,   43,  140,  142,  141,  143,
      147,  145,   64,   73,   67,   76,    0,  122,    0,   71,
       65,   69,   66,   70,   81,    0,   93,   72,   90,  101,
        0,    0,    0,    0,    0,    0,    0,  105,  104,  103,
      104,  103,   79,   74,   63,   75,   80,  144,  123,    0,

       78,  144,  144,  144,  144,  144,  144,  144,  144,  144,
        6,  144,  144,  144,  144,  144,  144,   14,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,   77,
       68,  139,  134,  133,  131,    0,  135,  132,  124,  125,
      138,  126,  127,  128,  129,  130,    0,    0,  121,    0,
        0,  122,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   84,   91,   92,    0,   88,   89,
        0,  100,   99,  100,   99,  102,   97,    0,   87,   82,
       83,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,   13,  144,  144,   18,  144,

      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  139,    0,  137,    0,  116,
        0,  115,    0,    0,  117,    0,  114,    0,  107,    0,
      108,    0,  120,    0,  109,    0,  110,    0,  111,    0,
      112,    0,  113,    0,    0,   93,    0,   90,   98,   96,
       95,   96,   95,   85,   86,  144,  144,  144,    1,  144,
        3,    4,  144,  144,  144,  144,   10,   11,  144,  144,
       16,  144,   19,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,   32,  144,  144,  136,    0,
        0,  118,    0,   94,   35,  144,  144,    2,    8,  144,

      144,  144,  144,   17,  144,  144,  144,  144,   20,  144,
      144,  144,  144,  144,  144,   30,  144,  144,   34,    0,
      119,  144,  144,  144,  144,    9,   12,   15,  144,  144,
       23,   24,   25,   26,   27,   28,  144,  144,  144,  144,
      144,  144,    7,  144,  144,   29,  144,  144,   36,  144,
        5,   22,   21,   31,   33,  144,   37,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   20,   20,    1,   21,   22,
       23,   24,   25,    1,   26,   27,   28,   26,   26,   29,
       30,   30,   31,   30,   30,   32,   30,   30,   30,   30,
       30,   30,   30,   30,   33,   30,   30,   34,   30,   30,
       35,   36,   37,   38,   39,    1,   40,   41,   42,   43,

       44,   45,   46,   47,   48,   30,   49,   50,   51,   52,
       53,   54,   30,   55,   56,   57,   58,   59,   60,   61,
       62,   63,   64,   65,   66,   67,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[68] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    3,    3,
        1,    1,    1,    1,    1,    4,    4,    4,    4,    5,
        5,    6,    6,    5,    1,    1,    1,    1,    5,    3,
        3,    3,    3,    3,    3,    5,    5,    5,    5,    6,
        5,    5,    5,    5,    5,    5,    5,    6,    5,    5,
        5,    5,    5,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[381] =
    {   0,
        0,    0,   65,   66,    0,    0,  657,  658,   70,   72,
      633,  658,  658,  632,   68,   68,  658,  658,  631,   65,
      658,   66,   64,  630,   89,   80,  658,   63,  629,   69,
        0,  101,  658,  658,  658,  628,   87,  592,  594,   79,
       50,   75,   67,  595,   83,  594,  602,   94,  583,  592,
      590,  595,  658,   64,  658,  658,  658,  658,  658,  152,
      658,  141,  658,  658,  658,  658,  632,  631,  209,  658,
      658,  658,  658,  658,  658,  623,  140,  658,  197,  162,
      219,   98,   47,  238,  271,  104,   84,  255,  107,  113,
      115,  114,  615,  658,  658,  658,  614,    0,  658,  140,

      658,  583,  582,  583,  576,  588,  575,  590,  577,  583,
      569,  570,  567,  567,  570,  567,  564,    0,  117,  568,
      143,  566,  120,  113,  570,  563,  131,  153,  568,  658,
      658,  219,  658,  658,  205,  212,  658,  658,  658,  658,
      658,  658,  658,  658,  658,  658,    0,  606,  605,  604,
      603,  602,  276,  601,  600,  599,  598,  597,  596,  595,
      594,  593,  592,  305,  658,  658,  658,  283,  658,  658,
      291,  175,  193,  186,  265,  658,  285,  301,  308,  658,
      658,  547,  548,  558,  544,  556,  551,  539,  203,  553,
      551,  547,  539,  545,  548,    0,  534,  538,    0,  539,

      536,  526,  524,  526,  528,  535,  521,  519,  519,  531,
      521,  525,  529,  531,  520,  290,  289,    0,  560,  559,
      558,  557,  320,  552,  546,  543,  542,  536,  530,  524,
      518,  512,  506,  500,  494,  488,  482,  476,  470,  462,
      456,  446,  426,  350,  336,  352,  342,  354,  658,  207,
      280,  283,  325,  658,  658,  384,  379,  386,    0,  382,
        0,    0,  373,  381,  370,  377,    0,    0,  371,  364,
        0,  368,    0,  363,  363,  362,  356,  368,  358,  362,
      367,  366,  364,  354,  357,    0,  344,  356,  658,  380,
      379,  378,  396,  658,    0,  335,  334,    0,    0,  328,

      324,  329,  320,    0,  327,  310,  318,  313,    0,  321,
      318,  310,  294,  297,  298,    0,  284,  274,    0,  291,
      267,  228,  215,  204,  198,    0,    0,    0,  204,  204,
        0,    0,    0,    0,    0,    0,  191,  188,  160,  144,
      162,  154,    0,  136,  129,    0,  132,  108,    0,   56,
        0,    0,    0,    0,    0,   33,    0,  658,  441,  447,
      453,  457,  463,  469,  473,  477,  483,  489,  495,  501,
      507,  513,  519,  525,  531,  537,  543,  547,  553,  559
    } ;

static const flex_int16_t yy_def[381] =
    {   0,
      358,    1,  359,  359,  360,  360,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  361,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      362,  362,  358,  358,  358,  358,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  363,  364,  364,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  362,  358,  361,

      358,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  365,  363,  363,  364,
      366,  367,  364,  368,  369,  370,  371,  372,  373,  374,
      375,  376,  377,  364,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  378,  358,  358,  358,
      358,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,

      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  358,  358,  365,  366,  366,
      367,  367,  364,  368,  368,  369,  369,  370,  370,  371,
      371,  372,  372,  373,  373,  374,  374,  375,  375,  376,
      376,  377,  377,  379,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  358,  380,
      379,  379,  379,  358,  362,  362,  362,  362,  362,  362,

      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  380,
      380,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,    0,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358
    } ;

static const flex_int16_t yy_nxt[726] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   26,
       27,   28,   29,   30,    8,   31,   31,   31,   31,   31,
       31,   32,   31,   31,   33,   34,   35,   36,   37,   38,
       39,   40,   41,   42,   43,   44,   31,   45,   31,   46,
       31,   31,   31,   31,   47,   48,   49,   50,   51,   52,
       31,   31,   31,   53,   54,   55,   56,   58,   58,   59,
       59,   62,   62,   62,   62,   65,   68,   71,  176,   76,
       73,   77,   77,   77,   93,   94,  130,   72,   74,   75,
       66,   96,   97,  110,  357,   79,  176,   88,   88,   88,

       60,   60,  111,   69,   79,   99,   80,   80,   81,  100,
      356,   89,   90,  102,  103,  176,  115,  104,  107,  116,
       82,   83,   84,   85,  112,  108,  113,  118,  131,   91,
      176,  109,   85,  176,  119,  114,  176,   92,   86,  176,
      122,  123,   62,   62,  176,  176,   87,  176,   68,   84,
      124,  355,  207,  125,  132,  176,  133,   77,   77,   77,
      134,  176,  176,  176,  176,  205,  198,  208,  166,  135,
      136,  167,  176,  199,  354,   69,  137,   79,  211,   80,
       80,   81,  206,  168,  166,  353,  212,  138,  201,  167,
      352,  139,  140,  172,  173,  141,  142,  351,  202,  203,

      213,  350,  214,  143,  349,   85,  144,  249,  145,  348,
      146,  174,  147,  151,   77,   77,   77,  152,  249,  175,
      216,  216,  217,  217,  249,  169,  153,  153,  170,  217,
      217,  347,  249,  154,   79,  346,   81,   81,   81,  294,
      171,  169,  249,  249,  155,  345,  170,  344,  156,  157,
       82,   83,  158,  159,  343,  177,  177,  177,  263,  264,
      160,  342,   85,  161,  294,  162,  341,  163,   86,  164,
       79,  340,   88,   88,   88,  321,   87,  177,  177,  177,
      177,  177,  177,  178,   68,  178,   89,   90,  179,  179,
      179,  216,  216,  223,  223,  245,  249,  245,   85,  321,

      246,  246,  246,  247,   91,  247,  289,  289,  248,  248,
      248,  294,   92,   68,  249,  294,  250,  251,  179,  179,
      179,  339,  244,  244,  244,  179,  179,  179,   68,  294,
      244,  244,  244,  244,  252,  338,  254,  290,  290,  255,
      294,  337,  253,  336,  244,  244,  244,  244,  244,  244,
      335,  334,  254,  246,  246,  246,  294,  255,  292,  248,
      248,  248,  333,  332,  331,  330,  329,  293,  293,  293,
      328,  327,  326,  325,  294,  293,  293,  293,  293,  324,
      166,  323,  169,  167,  322,  170,  292,  292,  321,  293,
      293,  293,  293,  293,  293,  168,  166,  171,  169,  319,

      318,  167,  317,  170,  292,  316,  315,  314,  313,  312,
      311,  310,  309,  293,  293,  293,  308,  307,  306,  305,
      304,  293,  293,  293,  293,  303,  302,  301,  300,  299,
      298,  297,  296,  295,  243,  293,  293,  293,  293,  293,
      293,   57,   57,   57,   57,   57,   57,   61,   61,   61,
       61,   61,   61,   67,  243,   67,   67,   67,   67,   98,
       98,   98,   98,  148,  241,  148,  148,  148,  148,  150,
      241,  150,  150,  150,  150,  218,  218,  219,  239,  219,
      219,  219,  219,  221,  239,  221,  221,  221,  221,  224,
      237,  224,  224,  224,  224,  226,  237,  226,  226,  226,

      226,  228,  235,  228,  228,  228,  228,  230,  235,  230,
      230,  230,  230,  232,  233,  232,  232,  232,  232,  234,
      233,  234,  234,  234,  234,  236,  231,  236,  236,  236,
      236,  238,  231,  238,  238,  238,  238,  240,  229,  240,
      240,  240,  240,  242,  229,  242,  242,  242,  242,  177,
      227,  227,  177,  291,  225,  291,  291,  291,  291,  320,
      225,  320,  320,  320,  320,  222,  222,  220,  220,  288,
      287,  286,  285,  284,  283,  282,  281,  280,  279,  278,
      277,  276,  275,  274,  273,  272,  271,  270,  269,  268,
      267,  266,  265,  262,  261,  260,  259,  258,  257,  256,

      243,  241,  239,  237,  235,  233,  231,  229,  227,  225,
      222,  220,   68,  149,  149,  215,  210,  209,  204,  200,
      197,  196,  195,  194,  193,  192,  191,  190,  189,  188,
      187,  186,  185,  184,  183,  182,  181,  180,  165,   68,
      149,  129,  128,  127,  126,  121,  120,  117,  106,  105,
      101,   95,   78,   70,   64,   63,  358,    7,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,

      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358
    } ;

static const flex_int16_t yy_chk[726] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    4,    3,
        4,    9,    9,   10,   10,   15,   16,   20,   83,   23,
       22,   23,   23,   23,   28,   28,   54,   20,   22,   22,
       15,   30,   30,   41,  356,   26,   83,   26,   26,   26,

        3,    4,   41,   16,   25,   32,   25,   25,   25,   32,
      350,   26,   26,   37,   37,   87,   43,   37,   40,   43,
       25,   25,   25,   26,   42,   40,   42,   45,   54,   26,
       82,   40,   25,   87,   45,   42,   86,   26,   25,   89,
       48,   48,   62,   62,   90,   92,   25,   91,  100,   25,
       48,  348,  124,   48,   60,   82,   60,   77,   77,   77,
       60,   86,   90,   92,   89,  123,  119,  124,   77,   60,
       60,   77,   91,  119,  347,  100,   60,   80,  127,   80,
       80,   80,  123,   77,   77,  345,  127,   60,  121,   77,
      344,   60,   60,   80,   80,   60,   60,  342,  121,  121,

      128,  341,  128,   60,  340,   80,   60,  172,   60,  339,
       60,   80,   60,   69,   79,   79,   79,   69,  174,   80,
      132,  132,  135,  135,  173,   79,   69,   69,   79,  136,
      136,  338,  172,   69,   81,  337,   81,   81,   81,  250,
       79,   79,  173,  174,   69,  330,   79,  329,   69,   69,
       81,   81,   69,   69,  325,   84,   84,   84,  189,  189,
       69,  324,   81,   69,  250,   69,  323,   69,   81,   69,
       88,  322,   88,   88,   88,  321,   81,   84,   84,   84,
       84,   84,   84,   85,  153,   85,   88,   88,   85,   85,
       85,  216,  216,  153,  153,  168,  175,  168,   88,  320,

      168,  168,  168,  171,   88,  171,  217,  217,  171,  171,
      171,  251,   88,  164,  175,  252,  177,  177,  178,  178,
      178,  318,  164,  164,  164,  179,  179,  179,  223,  251,
      164,  164,  164,  164,  177,  317,  179,  223,  223,  179,
      252,  315,  177,  314,  164,  164,  164,  164,  164,  164,
      313,  312,  179,  245,  245,  245,  253,  179,  244,  247,
      247,  247,  311,  310,  308,  307,  306,  244,  244,  244,
      305,  303,  302,  301,  253,  244,  244,  244,  244,  300,
      246,  297,  248,  246,  296,  248,  292,  291,  290,  244,
      244,  244,  244,  244,  244,  246,  246,  248,  248,  288,

      287,  246,  285,  248,  293,  284,  283,  282,  281,  280,
      279,  278,  277,  293,  293,  293,  276,  275,  274,  272,
      270,  293,  293,  293,  293,  269,  266,  265,  264,  263,
      260,  258,  257,  256,  243,  293,  293,  293,  293,  293,
      293,  359,  359,  359,  359,  359,  359,  360,  360,  360,
      360,  360,  360,  361,  242,  361,  361,  361,  361,  362,
      362,  362,  362,  363,  241,  363,  363,  363,  363,  364,
      240,  364,  364,  364,  364,  365,  365,  366,  239,  366,
      366,  366,  366,  367,  238,  367,  367,  367,  367,  368,
      237,  368,  368,  368,  368,  369,  236,  369,  369,  369,

      369,  370,  235,  370,  370,  370,  370,  371,  234,  371,
      371,  371,  371,  372,  233,  372,  372,  372,  372,  373,
      232,  373,  373,  373,  373,  374,  231,  374,  374,  374,
      374,  375,  230,  375,  375,  375,  375,  376,  229,  376,
      376,  376,  376,  377,  228,  377,  377,  377,  377,  378,
      227,  226,  378,  379,  225,  379,  379,  379,  379,  380,
      224,  380,  380,  380,  380,  222,  221,  220,  219,  215,
      214,  213,  212,  211,  210,  209,  208,  207,  206,  205,
      204,  203,  202,  201,  200,  198,  197,  195,  194,  193,
      192,  191,  190,  188,  187,  186,  185,  184,  183,  182,

      163,  162,  161,  160,  159,  158,  157,  156,  155,  154,
      152,  151,  150,  149,  148,  129,  126,  125,  122,  120,
      117,  116,  115,  114,  113,  112,  111,  110,  109,  108,
      107,  106,  105,  104,  103,  102,   97,   93,   76,   68,
       67,   52,   51,   50,   49,   47,   46,   44,   39,   38,
       36,   29,   24,   19,   14,   11,    7,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,

      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "assignment1.c"
#line 3 "assignment1.c"
#include"tokens-manual.h"

enum num_types {
	_CHAR,
	_UCHAR,
	_SHORT,
	_USHORT,
	_INT,
	_UINT,
	_LONG,
	_ULONG,
	_LONGLONG,
	_ULONGLONG,
	_FLOAT,
	_DOUBLE,
	_LDOUBLE,
};

typedef struct {
	unsigned char type;
	union {
		char c; 
		short s;
		int i;
		long l;
		long long ll;
		unsigned char uc;
		unsigned short us;
		unsigned int ui;
		unsigned long ul;
		unsigned long long ull;
		float f;
		double d;
		long double ld;
	} value;
} NUM;

int stringlen;

typedef struct {
	unsigned int length;
	char * string;
} STR;

int store_num(char * text, NUM * number, unsigned char type, int base) {
	number->type = type;
	switch (type) {
		case _CHAR:
			number->value.c = strtol(text,NULL,base);
			break;
		case _UCHAR:
			number->value.uc = strtol(text,NULL,base);
			break;
		case _SHORT:
			number->value.s = strtol(text,NULL,base);
			break;
		case _USHORT:
			number->value.us = strtol(text,NULL,base);
			break;
		case _INT:
			number->value.i = strtol(text,NULL,base);
			break;
		case _UINT:
			number->value.ui = strtol(text,NULL,base);
			break;
		case _LONG:
			number->value.l = strtol(text,NULL,base);
			break;
		case _ULONG:
			number->value.ul = strtol(text,NULL,base);
			break;
		case _LONGLONG:
			number->value.ll = strtol(text,NULL,base);
			break;
		case _ULONGLONG:
			number->value.ull = strtol(text,NULL,base);
			break;
		case _FLOAT:
			number->value.f = strtof(text,NULL);
			break;
		case _DOUBLE:
			number->value.d = strtof(text,NULL);
			break;
		case _LDOUBLE:
			number->value.ld = strtof(text,NULL);
			break;
	}
	return 0;
}

typedef union {
	NUM number;
	STR string;
	char charlit;
	char * ident;
} YYSTYPE;

YYSTYPE yylval;

char strbuff[1024];

#line 828 "lex.yy.c"

#line 830 "lex.yy.c"

#define INITIAL 0
#define instring 1
#define incomment 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 109 "assignment1.c"

#line 111 "assignment1.c"
	/* Keywords */
#line 1053 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 359 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 658 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 112 "assignment1.c"
return AUTO;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 113 "assignment1.c"
return BREAK;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 114 "assignment1.c"
return CASE;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 115 "assignment1.c"
return CHAR;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 116 "assignment1.c"
return CONTINUE;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 117 "assignment1.c"
return DO;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 118 "assignment1.c"
return DEFAULT;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 119 "assignment1.c"
return CONST;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 120 "assignment1.c"
return DOUBLE;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 121 "assignment1.c"
return ELSE;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 122 "assignment1.c"
return ENUM;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 123 "assignment1.c"
return EXTERN;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 124 "assignment1.c"
return FOR;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 125 "assignment1.c"
return IF;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 126 "assignment1.c"
return INLINE;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 127 "assignment1.c"
return GOTO;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 128 "assignment1.c"
return FLOAT;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 129 "assignment1.c"
return INT;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 130 "assignment1.c"
return LONG;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 131 "assignment1.c"
return SHORT;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 132 "assignment1.c"
return RESTRICT;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 133 "assignment1.c"
return REGISTER;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 134 "assignment1.c"
return RETURN;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 135 "assignment1.c"
return SIGNED;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 136 "assignment1.c"
return SIZEOF;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 137 "assignment1.c"
return STATIC;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 138 "assignment1.c"
return STRUCT;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 139 "assignment1.c"
return SWITCH;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 140 "assignment1.c"
return TYPEDEF;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 141 "assignment1.c"
return UNION;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 142 "assignment1.c"
return UNSIGNED;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 143 "assignment1.c"
return VOID;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 144 "assignment1.c"
return VOLATILE;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 145 "assignment1.c"
return WHILE;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 146 "assignment1.c"
return _BOOL;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 147 "assignment1.c"
return _COMPLEX;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 148 "assignment1.c"
return _IMAGINARY;
	YY_BREAK
/* Special Characters */
case 38:
YY_RULE_SETUP
#line 151 "assignment1.c"
return '=';
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 152 "assignment1.c"
return ',';
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 153 "assignment1.c"
return ';';
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 154 "assignment1.c"
return '.';
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 155 "assignment1.c"
return '!';
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 156 "assignment1.c"
return '~';
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 157 "assignment1.c"
return '#';
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 158 "assignment1.c"
return '\\';
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 159 "assignment1.c"
return '&';
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 160 "assignment1.c"
return '*';
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 161 "assignment1.c"
return '+';
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 162 "assignment1.c"
return '-';
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 163 "assignment1.c"
return '/';
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 164 "assignment1.c"
return '^';
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 165 "assignment1.c"
return '|';
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 166 "assignment1.c"
return '_';
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 167 "assignment1.c"
return '%';
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 168 "assignment1.c"
return '>';
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 169 "assignment1.c"
return '<';
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 170 "assignment1.c"
return '{';
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 171 "assignment1.c"
return '}';
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 172 "assignment1.c"
return '(';
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 173 "assignment1.c"
return ')';
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 174 "assignment1.c"
return '[';
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 175 "assignment1.c"
return ']';
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 177 "assignment1.c"
return EQEQ;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 178 "assignment1.c"
return NOTEQ;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 179 "assignment1.c"
return PLUSPLUS;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 180 "assignment1.c"
return MINUSMINUS;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 181 "assignment1.c"
return LOGAND;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 182 "assignment1.c"
return LOGOR;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 183 "assignment1.c"
return PLUSEQ;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 184 "assignment1.c"
return MINUSEQ;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 185 "assignment1.c"
return TIMESEQ;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 186 "assignment1.c"
return DIVEQ;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 187 "assignment1.c"
return MODEQ;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 188 "assignment1.c"
return LTEQ;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 189 "assignment1.c"
return GTEQ;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 190 "assignment1.c"
return ANDEQ;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 191 "assignment1.c"
return OREQ;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 192 "assignment1.c"
return XOREQ;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 193 "assignment1.c"
return SHL;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 194 "assignment1.c"
return SHR;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 195 "assignment1.c"
return INDSEL;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 197 "assignment1.c"
return SHLEQ;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 198 "assignment1.c"
return SHREQ;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 199 "assignment1.c"
return ELLIPSIS;
	YY_BREAK
/* Numeric Literals */
case 85:
YY_RULE_SETUP
#line 203 "assignment1.c"
{
	store_num(yytext,&yylval.number,_FLOAT,10); return NUMBER;
}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 207 "assignment1.c"
{
	store_num(yytext,&yylval.number,_LDOUBLE,10); return NUMBER;
}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 211 "assignment1.c"
{
	store_num(yytext,&yylval.number,_DOUBLE,10); return NUMBER;
}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 215 "assignment1.c"
{
	store_num(yytext,&yylval.number,_FLOAT,10); return NUMBER;
}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 219 "assignment1.c"
{
	store_num(yytext,&yylval.number,_LDOUBLE,10); return NUMBER;
}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 223 "assignment1.c"
{
	store_num(yytext,&yylval.number,_DOUBLE,10); return NUMBER;
}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 227 "assignment1.c"
{
	store_num(yytext,&yylval.number,_FLOAT,10); return NUMBER;
}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 231 "assignment1.c"
{
	store_num(yytext,&yylval.number,_LDOUBLE,10); return NUMBER;
}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 235 "assignment1.c"
{
	store_num(yytext,&yylval.number,_DOUBLE,10); return NUMBER;
}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 239 "assignment1.c"
{
	store_num(yytext,&yylval.number,_ULONG,16); return NUMBER;
}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 243 "assignment1.c"
{
	store_num(yytext,&yylval.number,_UINT,16); return NUMBER;
}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 247 "assignment1.c"
{
	store_num(yytext,&yylval.number,_LONG,16); return NUMBER;
}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 251 "assignment1.c"
{
	store_num(yytext,&yylval.number,_INT,16); return NUMBER;
}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 255 "assignment1.c"
{
	store_num(yytext,&yylval.number,_ULONG,8); return NUMBER;
}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 259 "assignment1.c"
{
	store_num(yytext,&yylval.number,_UINT,8); return NUMBER;
}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 263 "assignment1.c"
{
	store_num(yytext,&yylval.number,_LONG,8); return NUMBER;
}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 267 "assignment1.c"
{
	store_num(yytext,&yylval.number,_INT,8); return NUMBER;
}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 271 "assignment1.c"
{
	store_num(yytext,&yylval.number,_ULONG,10); return NUMBER;
}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 275 "assignment1.c"
{
	store_num(yytext,&yylval.number,_UINT,10); return NUMBER;
}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 279 "assignment1.c"
{
	store_num(yytext,&yylval.number,_LONG,10); return NUMBER;
}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 283 "assignment1.c"
{
	store_num(yytext,&yylval.number,_INT,10); return NUMBER;
}	
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 287 "assignment1.c"
{
	store_num(yytext,&yylval.number,_INT,10); return NUMBER;
}
	YY_BREAK
/* Character Literals */
case 107:
YY_RULE_SETUP
#line 292 "assignment1.c"
{
	yylval.charlit = '\a'; return CHARLIT;
}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 295 "assignment1.c"
{
	yylval.charlit = '\b'; return CHARLIT;
}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 298 "assignment1.c"
{
	yylval.charlit = '\f'; return CHARLIT;
}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 301 "assignment1.c"
{
	yylval.charlit = '\n'; return CHARLIT;
}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 304 "assignment1.c"
{
	yylval.charlit = '\r'; return CHARLIT;
}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 307 "assignment1.c"
{
	yylval.charlit = '\t'; return CHARLIT;
}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 310 "assignment1.c"
{
	yylval.charlit = '\v'; return CHARLIT;
}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 313 "assignment1.c"
{
	yylval.charlit = '\\'; return CHARLIT;
}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 316 "assignment1.c"
{
	yylval.charlit = '\''; return CHARLIT;
}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 319 "assignment1.c"
{
	yylval.charlit = '\"'; return CHARLIT;
}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 322 "assignment1.c"
{
	yylval.charlit = '\?'; return CHARLIT;
}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 325 "assignment1.c"
{
	if (yytext[0] == 'L') 
		yylval.charlit = strtol(yytext+2,NULL,16);
	else
		yylval.charlit = strtol(yytext+1,NULL,16);
	return CHARLIT;
}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 332 "assignment1.c"
{
	if (yytext[0] == 'L')
		yylval.charlit = strtol(yytext+2,NULL,8);
	else
		yylval.charlit = strtol(yytext+1,NULL,8);
	return CHARLIT;
}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 339 "assignment1.c"
{
	yylval.charlit = '\e'; return CHARLIT;
}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 342 "assignment1.c"
{
	if (yytext[0] == 'L') 
		yylval.charlit = yytext[2];
	else
		yylval.charlit = yytext[1]; 
	return CHARLIT;
}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 349 "assignment1.c"
{
	return -1;
}
	YY_BREAK
/* String Literals */
case 123:
YY_RULE_SETUP
#line 354 "assignment1.c"
{
	BEGIN(instring); stringlen=0;
}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 358 "assignment1.c"
strbuff[stringlen++] = '\a';
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 359 "assignment1.c"
strbuff[stringlen++] = '\b';
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 360 "assignment1.c"
strbuff[stringlen++] = '\f';
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 361 "assignment1.c"
strbuff[stringlen++] = '\n';
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 362 "assignment1.c"
strbuff[stringlen++] = '\r';
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 363 "assignment1.c"
strbuff[stringlen++] = '\t';
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 364 "assignment1.c"
strbuff[stringlen++] = '\v';
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 365 "assignment1.c"
strbuff[stringlen++] = '\0';
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 366 "assignment1.c"
strbuff[stringlen++] = '\\';
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 367 "assignment1.c"
strbuff[stringlen++] = '\'';
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 368 "assignment1.c"
strbuff[stringlen++] = '\"';
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 369 "assignment1.c"
strbuff[stringlen++] = '\?';
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 370 "assignment1.c"
yytext[0] = '0'; strbuff[stringlen++] = strtol(yytext,NULL,8);
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 371 "assignment1.c"
yytext[0] = '0'; strbuff[stringlen++] = strtol(yytext,NULL,16);
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 372 "assignment1.c"
strbuff[stringlen++] = '\e';
	YY_BREAK
case 139:
/* rule 139 can match eol */
YY_RULE_SETUP
#line 373 "assignment1.c"
/* Do nothing */
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 374 "assignment1.c"
strbuff[stringlen++] = yytext[0];
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 375 "assignment1.c"
{
	strbuff[stringlen++] = '\0';
	yylval.string.string = malloc(stringlen);
	yylval.string.length = stringlen;
	memcpy(yylval.string.string,strbuff,stringlen);
	BEGIN(0);
	return STRING;
}
	YY_BREAK
case 142:
/* rule 142 can match eol */
YY_RULE_SETUP
#line 383 "assignment1.c"
BEGIN(0); return -1;
	YY_BREAK
case YY_STATE_EOF(instring):
#line 384 "assignment1.c"
BEGIN(0); return -1;
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 385 "assignment1.c"
BEGIN(0); return -1;
	YY_BREAK
/* Identifiers */
case 144:
YY_RULE_SETUP
#line 388 "assignment1.c"
{
	yylval.ident = malloc(strlen(yytext));
	memcpy(yylval.ident,yytext,strlen(yytext)+1);
	return IDENT;
}
	YY_BREAK
case 145:
/* rule 145 can match eol */
YY_RULE_SETUP
#line 394 "assignment1.c"
/* eat up whitespace */
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 395 "assignment1.c"
return -1;
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 396 "assignment1.c"
ECHO;
	YY_BREAK
#line 1958 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(incomment):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 359 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 359 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 358);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 396 "assignment1.c"


#include <fcntl.h>
#include <sys/types.h>
#include <sys/stat.h>

void main() {
	int yyret;
	yyin = fopen("kw.c","r");
	while ((yyret = yylex()) != TOKEOF) {
		if (yyret == NUMBER) {
			printf("NUMBER\t");
			switch (yylval.number.type) {
				case _CHAR:
					printf("char %hhd\n",yylval.number.value.c);
					break;
				case _UCHAR:
					printf("unsigned char%hhu\n",yylval.number.value.uc);
					break;
				case _SHORT:
					printf("short %hd\n",yylval.number.value.s);
					break;
				case _USHORT:
					printf("unsigned short%hu\n",yylval.number.value.us);
					break;
				case _INT:
					printf("int %d\n",yylval.number.value.i);
					break;
				case _UINT:
					printf("unsigned int %u\n",yylval.number.value.ui);
					break;
				case _LONG:
					printf("long %ld\n",yylval.number.value.l);
					break;
				case _ULONG:
					printf("unsigned long%lu\n",yylval.number.value.ul);
					break;
				case _LONGLONG:
					printf("long long %lld\n",yylval.number.value.ll);
					break;
				case _ULONGLONG:
					printf("unsigned long long %llu\n",yylval.number.value.ull);
					break;
				case _FLOAT:
					printf("float %f\n",yylval.number.value.f);
					break;
				case _DOUBLE:
					printf("double %f\n",yylval.number.value.d);
					break;
				case _LDOUBLE:
					printf("long double %Lf\n",yylval.number.value.ld);
					break;
			}
		}
		else if (yyret == CHARLIT) {
			printf("%c\n",yylval.charlit);
		}
		else if (yyret == STRING) {
			printf("%s\n",yylval.string.string);
		}
		else if (yyret == IDENT) {
			printf("IDENT\t%s\n",yylval.ident);
		}
		else if (yyret < 257 && yyret >= 0) {
			printf("%c\n",yyret);
		}
		else if (yyret == -1) {
			fprintf(stderr,"somethings wrong\n");
		}
		
		else
			printf("%d\n",yyret);
	}
}
